USE [USUARIOS]
GO
/****** Object:  Table [dbo].[USUARIOS]    Script Date: 06/14/2013 11:23:41 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[USUARIOS](
	[usu_codigo] [int] IDENTITY(1,1) NOT NULL,
	[usu_nome] [varchar](150) NOT NULL,
	[usu_login] [varchar](100) NOT NULL,
	[usu_senha] [varchar](255) NOT NULL,
 CONSTRAINT [PK_USUARIOS] PRIMARY KEY CLUSTERED 
(
	[usu_codigo] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

